name: joda
description: A time library vaguely based on [Joda Time](https://www.joda.org/joda-time/).
version: 0.0.1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  timezone: ^0.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
